part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const SPLASH = _Paths.SPLASH;
  static const AUTH_LOGIN = _Paths.AUTH_LOGIN;
  static const AUTH_SIGN_UP = _Paths.AUTH_SIGN_UP;
  static const AUTH_VERIFY_ACCOUNT = _Paths.AUTH_VERIFY_ACCOUNT;
  static const AUTH_NEW_PASSWORD = _Paths.AUTH_NEW_PASSWORD;
  static const BOTTOM_NAV = _Paths.BOTTOM_NAV;
  static const UPDATE_PROFILE = _Paths.UPDATE_PROFILE;
  static const USER_BASIC_PROFILE = _Paths.USER_BASIC_PROFILE;
  static const DISCOVER_PUBLIC_PROFILE = _Paths.DISCOVER_PUBLIC_PROFILE;
  static const LEADER_BOARD = _Paths.LEADER_BOARD;
  static const AGENCY_ACCESS = _Paths.AGENCY_ACCESS;
  static const AGENCY_HOST_ONBOARDING = _Paths.AGENCY_HOST_ONBOARDING;
  static const AGENCY_HOST_STATUS = _Paths.AGENCY_HOST_STATUS;
  static const AGENCY_OWNER_REGISTER = _Paths.AGENCY_OWNER_REGISTER;
  static const AGENCY_OWNER_STATUS = _Paths.AGENCY_OWNER_STATUS;
  static const AGENCY_RECRUIT_LINK = _Paths.AGENCY_RECRUIT_LINK;
  static const AGENCY_HOST_LIST = _Paths.AGENCY_HOST_LIST;
  static const AGENCY_PENDING_HOSTS = _Paths.AGENCY_PENDING_HOSTS;
  static const AGENCY_REVENUE = _Paths.AGENCY_REVENUE;
  static const LIVE_ACTION = _Paths.LIVE_ACTION;
  static const JOIN_LIVE = _Paths.JOIN_LIVE;
  static const LIVE_ROOM_CREATE = _Paths.LIVE_ROOM_CREATE;
  static const LIVE_BROADCAST = _Paths.LIVE_BROADCAST;
  static const MESSAGES_LIST = _Paths.MESSAGES_LIST;
  static const CHAT_DETAIL = _Paths.CHAT_DETAIL;
  static const CHAT_CONTACT_PROFILE = _Paths.CHAT_CONTACT_PROFILE;
  static const CHAT_VOICE_CALL = _Paths.CHAT_VOICE_CALL;
  static const FOLLOW_LIST = _Paths.FOLLOW_LIST;
  static const SETTINGS = _Paths.SETTINGS;
  static const BLOCK_LIST = _Paths.BLOCK_LIST;
  static const USER_LEVEL = _Paths.USER_LEVEL;
  static const BACKPACK = _Paths.BACKPACK;
  static const MALL = _Paths.MALL;
  static const SVIP = _Paths.SVIP;
  static const FAMILY = _Paths.FAMILY;
  static const VISITORS = _Paths.VISITORS;
  static const ARISTOCRACY_CENTER = _Paths.ARISTOCRACY_CENTER;
  static const ACTIVITY = _Paths.ACTIVITY;
  static const POINT_CENTER = _Paths.POINT_CENTER;
  static const AWARD = _Paths.AWARD;
  static const BROADCAST_WATCHED = _Paths.BROADCAST_WATCHED;
  static const TRANSACTION_HISTORY = _Paths.TRANSACTION_HISTORY;
  static const GIFT_TRANSACTIONS = _Paths.GIFT_TRANSACTIONS;
  static const VIP_STORE = _Paths.VIP_STORE;
  static const ENTRANCE_PATTI = _Paths.ENTRANCE_PATTI;
  static const LIVE_MODERATION = _Paths.LIVE_MODERATION;
  static const CUSTOMER_SERVICE = _Paths.CUSTOMER_SERVICE;
  static const PK_BATTLE = _Paths.PK_BATTLE;
  static const PK_V1_ARENA = _Paths.PK_V1_ARENA;
  static const PK_V1_HISTORY = _Paths.PK_V1_HISTORY;
  static const CALL = _Paths.CALL;
  static const COIN_SELLER = _Paths.COIN_SELLER;
  static const AGENCY_OWNER = _Paths.AGENCY_OWNER;
  static const SUPER_ADMIN_BOTTOM_NAV = _Paths.SUPER_ADMIN_BOTTOM_NAV;
  static const SUPER_ADMIN_AGENCY_DETAIL = _Paths.SUPER_ADMIN_AGENCY_DETAIL;
  static const SUPER_ADMIN_HOST_DETAIL = _Paths.SUPER_ADMIN_HOST_DETAIL;
}

abstract class _Paths {
  _Paths._();

  static const SPLASH = '/splash';
  static const AUTH_LOGIN = '/login';
  static const AUTH_SIGN_UP = '/sign-up';
  static const AUTH_VERIFY_ACCOUNT = '/verify-account';
  static const AUTH_NEW_PASSWORD = '/new-password';
  static const BOTTOM_NAV = '/bottom-nav';
  static const UPDATE_PROFILE = '/update-profile';
  static const USER_BASIC_PROFILE = '/user-basic-profile';
  static const DISCOVER_PUBLIC_PROFILE = '/discover-public-profile';
  static const LEADER_BOARD = '/leader-board';
  static const AGENCY_ACCESS = '/agency-access';
  static const AGENCY_HOST_ONBOARDING = '/agency-host-onboarding';
  static const AGENCY_HOST_STATUS = '/agency-host-status';
  static const AGENCY_OWNER_REGISTER = '/agency-owner-register';
  static const AGENCY_OWNER_STATUS = '/agency-owner-status';
  static const AGENCY_RECRUIT_LINK = '/agency-recruit-link';
  static const AGENCY_HOST_LIST = '/agency-host-list';
  static const AGENCY_PENDING_HOSTS = '/agency-pending-hosts';
  static const AGENCY_REVENUE = '/agency-revenue';
  static const LIVE_ACTION = '/live-action';
  static const JOIN_LIVE = '/join-live';
  static const LIVE_ROOM_CREATE = '/live-room-create';
  static const LIVE_BROADCAST = '/live-broadcast';
  static const MESSAGES_LIST = '/messages-list';
  static const CHAT_DETAIL = '/chat-detail';
  static const CHAT_CONTACT_PROFILE = '/chat-contact-profile';
  static const CHAT_VOICE_CALL = '/chat-voice-call';
  static const FOLLOW_LIST = '/follow-list';
  static const SETTINGS = '/settings';
  static const BLOCK_LIST = '/block-list';
  static const USER_LEVEL = '/user-level';
  static const BACKPACK = '/backpack';
  static const MALL = '/mall';
  static const SVIP = '/svip';
  static const FAMILY = '/family';
  static const VISITORS = '/visitors';
  static const ARISTOCRACY_CENTER = '/aristocracy-center';
  static const ACTIVITY = '/activity';
  static const POINT_CENTER = '/point-center';
  static const AWARD = '/award';
  static const BROADCAST_WATCHED = '/broadcast-watched';
  static const TRANSACTION_HISTORY = '/transaction-history';
  static const GIFT_TRANSACTIONS = '/gift-transactions';
  static const VIP_STORE = '/vip-store';
  static const ENTRANCE_PATTI = '/entrance-patti';
  static const LIVE_MODERATION = '/live-moderation';
  static const CUSTOMER_SERVICE = '/customer-service';
  static const PK_BATTLE = '/pk-battle';
  static const PK_V1_ARENA = '/pk-v1-arena';
  static const PK_V1_HISTORY = '/pk-v1-history';
  static const CALL = '/call';
  static const COIN_SELLER = '/coin-seller';
  static const AGENCY_OWNER = '/agency-owner';
  static const SUPER_ADMIN_BOTTOM_NAV = '/super-admin-bottom-nav';
  static const SUPER_ADMIN_AGENCY_DETAIL = '/super-admin-agency-detail';
  static const SUPER_ADMIN_HOST_DETAIL = '/super-admin-host-detail';
}
